name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none


environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  envied:
    path: ../../packages/envied

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^1.0.0
  test: ^1.16.0
  envied_generator:
    path: ../../packages/envied_generator