name: envied_generator
description: Generator for the Envied package. See https://pub.dev/packages/envied.
version: 0.3.0+3
repository: https://github.com/petercinibulk/envied
homepage: https://github.com/petercinibulk/envied

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  envied: ^0.3.0
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.1.0
  envied: 
    git:
      url: https://github.com/yasinarik/envied
      path: packages/envied

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
  source_gen_test: ^1.0.3
