name: envied
description: Explicitly reads environment variables into a dart file from a .env file for more security and faster start up times.
version: 0.3.1
repository: https://github.com/yasinarik/envied
homepage: https://github.com/yasinarik/envied

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
